/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author ISMAEL
 */
import clases.Aula;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import ventanas.ventanaNuevaAula;
public class ventanaAulas extends javax.swing.JFrame {
    
    /**
     * Creates new form Vgaulas
     */
    public ventanaAulas() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAula = new javax.swing.JTable();
        jButtonNuevo = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aulas registradas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        tablaAula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aula", "Capacidad", "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(tablaAula);

        jButtonNuevo.setText("Nuevo");

        jButtonEliminar.setText("Eliminar");

        jButtonEditar.setText("Editar");

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(305, 305, 305)
                            .addComponent(jButtonNuevo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSalir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEliminar)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonEliminar))
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }
    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }
    
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonEditar;
    public javax.swing.JButton jButtonEliminar;
    public javax.swing.JButton jButtonNuevo;
    public javax.swing.JButton jButtonSalir;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JTable tablaAula;
    // End of variables declaration//GEN-END:variables
    
    public static void mostrarRegitroNuevo(ventanaNuevaAula v, String op){
        v.setVisible(true);
        if("Nuevo".equals(op)){
            //v.jTextId.setText("");
            v.jTextAula.setText("");
            v.jTextCapacidad.setText("");
            v.jTextDescripcion.setText("");
        }
    }
    public static Object entregarRegistro(ventanaNuevaAula vistaNA){
        
        String au = vistaNA.jTextAula.getText().trim();
        int can = Integer.parseInt((String) vistaNA.jTextCapacidad.getText().trim());
        String des = vistaNA.jTextDescripcion.getText().trim();
        
        Object[] res = new Object[3];
        res[0] = au;
        res[1] = can;
        res[2] = des;
        return res;
    }
    public static int modificamos(ventanaAulas v, ventanaNuevaAula vn){
        int fila = v.tablaAula.getSelectedRow();
            if(fila <= -1){
                JOptionPane.showMessageDialog(v, "Debe seleccionar una fila");
            }
            if(fila > -1){
                vn.setVisible(true);
                String id = (String)v.tablaAula.getValueAt(fila, 0).toString();
                String aula = (String)v.tablaAula.getValueAt(fila, 1);
                String can = (String)v.tablaAula.getValueAt(fila, 2).toString();
                String des = (String)v.tablaAula.getValueAt(fila, 3);
                //vn.jTextId.setText(id);
                vn.jTextAula.setText(aula);
                vn.jTextCapacidad.setText(can);
                vn.jTextDescripcion.setText(des);
                
            }
        return fila;     
    }
    public static Object modificarRegistro(ventanaNuevaAula vistaNA){
        
        //int id = Integer.parseInt((String)vistaNA.jTextId.getText().trim());
        String aul = vistaNA.jTextAula.getText().trim();
        int can = Integer.parseInt((String)vistaNA.jTextCapacidad.getText().trim());
        String des = vistaNA.jTextDescripcion.getText().trim();
        Object[] res = new Object[4];
        //res[0] = id;
        res[1] = aul;
        res[2] = can;
        res[3] = des;
        return res;
    }
    public static void listarRegistros(ventanaAulas a , List v){
        Aula aula = new Aula();
        DefaultTableModel modeloT = new DefaultTableModel();
        JTable tabla = a.tablaAula;
        modeloT = (DefaultTableModel)tabla.getModel();
        modeloT.setRowCount(0);
        List<Aula>lista = v;
        Object[] object = new Object[4];
        for(int i=0 ; i<lista.size() ; i++){
            //object[0] = lista.get(i).getId();
            object[1] = lista.get(i).getNombre();
            object[2] = lista.get(i).getCantidad();
            object[3] = lista.get(i).getDescripcion();
            modeloT.addRow(object);  
        }
        a.tablaAula.setModel(modeloT);
    }
    public static int eliminarRegistro(ventanaAulas a){
       
        int fila = a.tablaAula.getSelectedRow();
        
        if (fila < -1){
            JOptionPane.showMessageDialog(a, "Debe seleccionar una fila");
        }else{
            int id = Integer.parseInt((String)a.tablaAula.getValueAt(fila, 0).toString());
            return id;
        }
        return -5;
    }
    
}


